services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-laravel-network

networks:
  shared-laravel-network:
    external: true
