name: Deploy

on: 
  push:
    branches: 
     - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote deploy commands
      uses: appleboy/ssh-action@v1.2.2  
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd webs/alerty.jaumelopez.dev
          git pull
          sail up -d --build
          bash start.sh